version: "3.7"


services:
    wsgi:
        build: ./
        container_name: "searchtube_wsgi"
        volumes:
            - ./web:/var/www/searchtube/web
            - ./.data/channels:/var/www/searchtube/data
            - ./searchtube:/usr/local/lib/python3.7/site-packages/searchtube
            - /var/log/apache2/:/var/log/apache2/
            - ./etc/apache2/sites-available/:/etc/apache2/sites-available/
            - ./etc/letsencrypt/:/etc/letsencrypt/
            # uncomment to mount test scripts in container
            # - ./tests:/tests 
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - .env

    mongo:
        image: mongo
        container_name: "searchtube_mongo"
        environment:
            MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
        volumes:
            - ./.data/db:/data/db:delegated

        # uncomment if you want mongobd to be accessible outside of docker
        # ports:
        #     - "27017:27017"
