version: "3.7"


services:
    wsgi:
        build: ./
        container_name: "rextube_wsgi"
        volumes:
            - ./web:/var/www/rextube/web
            - ./.data/channels:/var/www/rextube/data
            - ./rextube:/usr/local/lib/python3.7/site-packages/rextube
            - ./tests:/tests
        ports:
            - "80:80"
            - "443:443"
        env_file:
                - .env

    mongo:
        image: mongo
        container_name: "rextube_mongo"
        environment:
            MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
        volumes:
            - ./.data/db:/data/db:delegated
        ports:
            - "27017:27017"
